autodetect starttls and tcp_wrappers support
Signed-off-by: SJ <sj@acts.hu>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -696,8 +696,6 @@ enable_option_checking
 enable_static_build
 enable_clamd
 enable_memcached
-enable_starttls
-enable_tcpwrappers
 with_database
 with_clapf_user
 '
@@ -1320,8 +1318,6 @@ Optional Features:
   --enable-static-build   build statically linked executables (default: dynamically linked)
   --enable-clamd          build clamd antivirus support
   --enable-memcached      build memcached support
-  --enable-starttls       build starttls support
-  --enable-tcpwrappers    build tcpwrappers support
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -3439,8 +3435,6 @@ have_psql="no"
 have_tre="no"
 have_zip="no"
 have_zlib="no"
-have_starttls="no"
-have_tcpwrappers="no"
 have_gsl="no"
 
 timeout_binary=""
@@ -3512,26 +3506,7 @@ fi
 
 
 
-# Check whether --enable-starttls was given.
-if test "${enable_starttls+set}" = set; then :
-  enableval=$enable_starttls; have_starttls=$enableval
-else
-  have_starttls="no"
-fi
-
-
-
-# Check whether --enable-tcpwrappers was given.
-if test "${enable_tcpwrappers+set}" = set; then :
-  enableval=$enable_tcpwrappers; want_tcpwrappers=$enableval
-else
-  want_tcpwrappers="no"
-fi
-
-
-
-if test "$want_tcpwrappers" = "yes"; then
-   for ac_header in tcpd.h
+for ac_header in tcpd.h
 do :
   ac_fn_c_check_header_mongrel "$LINENO" "tcpd.h" "ac_cv_header_tcpd_h" "$ac_includes_default"
 if test "x$ac_cv_header_tcpd_h" = xyes; then :
@@ -3545,7 +3520,7 @@ fi
 
 done
 
-   { $as_echo "$as_me:${as_lineno-$LINENO}: checking for hosts_access in -lwrap" >&5
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for hosts_access in -lwrap" >&5
 $as_echo_n "checking for hosts_access in -lwrap... " >&6; }
 if ${ac_cv_lib_wrap_hosts_access+:} false; then :
   $as_echo_n "(cached) " >&6
@@ -3627,10 +3602,9 @@ fi
 fi
 ac_cv_lib_wrap=ac_cv_lib_wrap_main
 
-   if test "$have_tcpwrappers" = "no"; then
-      echo "can't find either tcpd.h or libwrap";
-      exit 1;
-   fi
+if test "$have_tcpwrappers" = "no"; then
+   echo "can't find either tcpd.h or libwrap";
+   exit 1;
 fi
 
 
@@ -4578,15 +4552,6 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
    antispam_libs="$antispam_libs -lzip"
-fi
-
-if test "$have_starttls" = "yes"; then
-   echo "starttls support: yes"
-
-cat >>confdefs.h <<_ACEOF
-#define HAVE_STARTTLS 1
-_ACEOF
-
 fi
 
 if test "$have_tcpwrappers" = "yes"; then
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -41,8 +41,6 @@ have_psql="no"
 have_tre="no"
 have_zip="no"
 have_zlib="no"
-have_starttls="no"
-have_tcpwrappers="no"
 have_gsl="no"
 
 timeout_binary=""
@@ -101,22 +99,12 @@ AC_ARG_ENABLE(memcached,
         [  --enable-memcached      build memcached support], want_memcached=$enableval, want_memcached="no")
 
 
-AC_ARG_ENABLE(starttls,
-	[  --enable-starttls       build starttls support], have_starttls=$enableval, have_starttls="no")
+AC_CHECK_HEADERS(tcpd.h, have_tcpwrappers=yes, have_tcpwrappers=no)
+AC_CHECK_LIB([wrap],[hosts_access],[AC_CHECK_LIB(wrap, hosts_access, have_tcpwrappers=yes, echo "libwrap is not found"; have_tcpwrappers=no)],[],[])ac_cv_lib_wrap=ac_cv_lib_wrap_main
 
-
-AC_ARG_ENABLE(tcpwrappers,
-	[  --enable-tcpwrappers    build tcpwrappers support], want_tcpwrappers=$enableval, want_tcpwrappers="no")
-
-
-if test "$want_tcpwrappers" = "yes"; then
-   AC_CHECK_HEADERS(tcpd.h, have_tcpwrappers=yes, have_tcpwrappers=no)
-   AC_CHECK_LIB([wrap],[hosts_access],[AC_CHECK_LIB(wrap, hosts_access, have_tcpwrappers=yes, echo "libwrap is not found"; have_tcpwrappers=no)],[],[])ac_cv_lib_wrap=ac_cv_lib_wrap_main
-
-   if test "$have_tcpwrappers" = "no"; then
-      echo "can't find either tcpd.h or libwrap";
-      exit 1;
-   fi
+if test "$have_tcpwrappers" = "no"; then
+   echo "can't find either tcpd.h or libwrap";
+   exit 1;
 fi
 
 
@@ -371,11 +359,6 @@ if test "$have_zip" = "yes"; then
    echo "zip library: yes"
    AC_DEFINE_UNQUOTED(HAVE_ZIP, 1, [libzip support])
    antispam_libs="$antispam_libs -lzip"
-fi
-
-if test "$have_starttls" = "yes"; then
-   echo "starttls support: yes"
-   AC_DEFINE_UNQUOTED(HAVE_STARTTLS, 1, [starttls support])
 fi
 
 if test "$have_tcpwrappers" = "yes"; then
