sqlite3 support - cgis not included yet

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1280,7 +1280,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-userdb[=ldap|mysql]      use either ldap or mysql database holding user data (default: none)
-  --with-tokendb[=cdb|mysql]      use either cdb or mysql database holding user data (default: none)
+  --with-tokendb[=cdb|mysql|sqlite3]      use either cdb, mysql or sqlite3 database holding user data (default: none)
   --with-qcache[=tcp|socket]      use Qcache via either a TCP or Unix domain socket (default: none)
 
 Some influential environment variables:
@@ -3703,6 +3703,7 @@ have_blackhole="no"
 have_cgi="no"
 have_train="no"
 have_mysql="no"
+have_sqlite3="no"
 have_ldap="no"
 have_surbl="no"
 have_gsl="no"
@@ -3713,6 +3714,7 @@ objs=""
 user_obj=""
 mysql_obj=""
 ldap_libs=""
+sqlite3_libs=""
 os=`uname -s`
 keep_old_token_format="no"
 
@@ -4899,7 +4901,6 @@ done
 
 
 
-
     # Check whether --enable-blackhole was given.
 if test "${enable_blackhole+set}" = set; then
   enableval=$enable_blackhole; want_blackhole=$enableval
@@ -4960,6 +4961,285 @@ if test "${with_tokendb+set}" = set; then
   if test "$withval" != "no" -a "$withval" != "yes"; then
     TOKENDB=$withval
   fi
+
+  if test "$withval" = "sqlite3"; then
+
+for ac_header in sqlite3.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  { echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+ have_sqlite3=yes
+else
+  echo "sqlite3.h is not found"
+fi
+
+done
+
+
+    { echo "$as_me:$LINENO: checking for main in -lsqlite3" >&5
+echo $ECHO_N "checking for main in -lsqlite3... $ECHO_C" >&6; }
+if test "${ac_cv_lib_sqlite3_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsqlite3  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_sqlite3_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_sqlite3_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_sqlite3_main" >&5
+echo "${ECHO_T}$ac_cv_lib_sqlite3_main" >&6; }
+if test $ac_cv_lib_sqlite3_main = yes; then
+  { echo "$as_me:$LINENO: checking for sqlite3_open in -lsqlite3" >&5
+echo $ECHO_N "checking for sqlite3_open in -lsqlite3... $ECHO_C" >&6; }
+if test "${ac_cv_lib_sqlite3_sqlite3_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsqlite3  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char sqlite3_open ();
+int
+main ()
+{
+return sqlite3_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_sqlite3_sqlite3_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_sqlite3_sqlite3_open=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_sqlite3_sqlite3_open" >&5
+echo "${ECHO_T}$ac_cv_lib_sqlite3_sqlite3_open" >&6; }
+if test $ac_cv_lib_sqlite3_sqlite3_open = yes; then
+  have_sqlite3=yes
+else
+  have_sqlite3=no
+fi
+
+fi
+ac_cv_lib_sqlite3=ac_cv_lib_sqlite3_main
+
+
+      if test "$have_sqlite3" = "no"; then
+           echo "sqlite3 not found";
+           exit 1;
+      fi
+
+  fi
+
 
 fi
 
@@ -5288,6 +5568,15 @@ if test "$TOKENDB" = "mysql"; then
    mysql_obj="mysql.o sql.o"
 fi
 
+if test "$TOKENDB" = "sqlite3"; then
+   if test "$have_sqlite3" = "no"; then
+      echo "please check your sqlite3 installation"
+      exit 1
+   fi
+   defs="$defs -DHAVE_SQLITE3"
+   sqlite3_libs="-lsqlite3"
+   mysql_obj="sqlite3.o sql.o"
+fi
 
 
 if test "$os" = "FreeBSD"; then
@@ -5461,7 +5750,7 @@ echo; echo
 
 
 CFLAGS="-O2 -Wall"
-LIBS="$libclamav $antispam_libs $gsl_libs"
+LIBS="$libclamav $antispam_libs $gsl_libs $sqlite3_libs"
 OBJS="misc.o cfg.o smtp.o sig.o session.o decoder.o parser.o cgi.o $objs"
 
 ac_config_files="$ac_config_files Makefile"
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -42,6 +42,7 @@ have_blackhole="no"
 have_cgi="no"
 have_train="no"
 have_mysql="no"
+have_sqlite3="no"
 have_ldap="no"
 have_surbl="no"
 have_gsl="no"
@@ -52,6 +53,7 @@ objs=""
 user_obj=""
 mysql_obj=""
 ldap_libs=""
+sqlite3_libs=""
 os=`uname -s`
 keep_old_token_format="no"
 
@@ -213,7 +215,6 @@ AC_ARG_ENABLE(antispam,
     fi
 
 
-
     dnl the blackhole feature
 
     AC_ARG_ENABLE(blackhole,
@@ -258,10 +259,23 @@ AC_ARG_WITH(userdb,
 
 
 AC_ARG_WITH(tokendb,
-[  --with-tokendb[[=cdb|mysql]]      use either cdb or mysql database holding user data (default: none)],[
+[  --with-tokendb[[=cdb|mysql|sqlite3]]      use either cdb, mysql or sqlite3 database holding user data (default: none)],[
   if test "$withval" != "no" -a "$withval" != "yes"; then
     TOKENDB=$withval
   fi
+
+  if test "$withval" = "sqlite3"; then
+    AC_CHECK_HEADERS(sqlite3.h, have_sqlite3=yes, echo "sqlite3.h is not found")
+
+    AC_HAVE_LIBRARY(sqlite3, AC_CHECK_LIB(sqlite3, sqlite3_open, have_sqlite3=yes, have_sqlite3=no))
+
+      if test "$have_sqlite3" = "no"; then
+           echo "sqlite3 not found";
+           exit 1;
+      fi
+
+  fi
+
 ])
 
 
@@ -318,6 +332,15 @@ if test "$TOKENDB" = "mysql"; then
    mysql_obj="mysql.o sql.o"
 fi
 
+if test "$TOKENDB" = "sqlite3"; then
+   if test "$have_sqlite3" = "no"; then
+      echo "please check your sqlite3 installation"
+      exit 1
+   fi
+   defs="$defs -DHAVE_SQLITE3"
+   sqlite3_libs="-lsqlite3"
+   mysql_obj="sqlite3.o sql.o"
+fi
 
 dnl let us know if we are building on FreeBSD
 
@@ -494,7 +517,7 @@ echo; echo
 
 
 CFLAGS="-O2 -Wall"
-LIBS="$libclamav $antispam_libs $gsl_libs"
+LIBS="$libclamav $antispam_libs $gsl_libs $sqlite3_libs"
 OBJS="misc.o cfg.o smtp.o sig.o session.o decoder.o parser.o cgi.o $objs"
 
 AC_OUTPUT(Makefile)
