added a store option

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -731,11 +731,11 @@ enable_rbl
 enable_all_received
 enable_blackhole
 with_userdb
+with_store
 enable_policy
 with_tokendb
 enable_lmtp
 enable_language_detection
-enable_outgoing_smtp
 enable_spamsum
 with_clapf_user
 enable_spamdrop_helper
@@ -1382,7 +1382,6 @@ Optional Features:
   --enable-policy         enable the policy feature
   --enable-lmtp           use LMTP local delivery (default: SMTP)
   --enable-language-detection use the language detection feature (experimental)
-  --enable-outgoing-smtp  enable outgoing SMTP server mode
   --enable-spamsum        enable spamsum support (experimental)
   --enable-spamdrop-helper use external spamdrop helper program
 
@@ -1390,6 +1389,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-userdb[=mysql|ldap]      use either ldap or mysql database holding user data (default: none)
+  --with-store[=mysql|fs]         use either mysql database or the local filesystem to keep emails (default: none)
   --with-tokendb[=mysql|sqlite3]  use either mysql or sqlite3 database holding tokens (default: none)
   --with-clapf-user=username      what user the clapf daemon shall be run as
 
@@ -3884,7 +3884,6 @@ sqlite3_libs=""
 spamsum_libs=""
 os=`uname -s`
 
-want_outgoing_smtp="no"
 want_language_detection="no"
 
 
@@ -5431,6 +5430,74 @@ fi
 
 
 
+
+# Check whether --with-store was given.
+if test "${with_store+set}" = set; then
+  withval=$with_store;
+  if test "$withval" != "no" -a "$withval" != "yes"; then
+    STORE=$withval
+  fi
+
+  if test "$withval" = "mysql"; then
+     # Extract the first word of "mysql_config", so it can be a program name with args.
+set dummy mysql_config; ac_word=$2
+{ $as_echo "$as_me:$LINENO: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if test "${ac_cv_prog_MYSQL_CONFIG+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$MYSQL_CONFIG"; then
+  ac_cv_prog_MYSQL_CONFIG="$MYSQL_CONFIG" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_MYSQL_CONFIG="yes"
+    $as_echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+MYSQL_CONFIG=$ac_cv_prog_MYSQL_CONFIG
+if test -n "$MYSQL_CONFIG"; then
+  { $as_echo "$as_me:$LINENO: result: $MYSQL_CONFIG" >&5
+$as_echo "$MYSQL_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+
+     if test x$MYSQL_CONFIG = xyes; then
+       have_mysql="yes"
+     fi
+
+     if test "$have_mysql" = "yes"; then
+
+            mysql_includes=`mysql_config --cflags`
+            mysql_libs=`mysql_config --libs_r`
+     else
+        echo "MySQL support is not found"
+        exit 1;
+     fi
+   fi
+
+
+fi
+
+
+
+
+
 # Check whether --enable-policy was given.
 if test "${enable_policy+set}" = set; then
   enableval=$enable_policy; want_policy=$enableval
@@ -5854,26 +5921,6 @@ else
   want_language_detection="no"
 fi
 
-
-
-
-
-
-    # Check whether --enable-outgoing-smtp was given.
-if test "${enable_outgoing_smtp+set}" = set; then
-  enableval=$enable_outgoing_smtp; want_outgoing_smtp=$enableval
-else
-  want_outgoing_smtp="no"
-fi
-
-
-    if test "$want_outgoing_smtp" = "yes"; then
-
-cat >>confdefs.h <<_ACEOF
-#define OUTGOING_SMTP 1
-_ACEOF
-
-    fi
 
 
 
@@ -6427,10 +6474,14 @@ if test "$TOKENDB" = "sqlite3"; then
    db_install="install-sqlite3"
 fi
 
-if test "$have_store" = "yes"; then
-   echo "store: clapfstore"
-else
-   echo "store: internal"
+if test "$STORE" = "mysql"; then
+   echo "message store: mysql"
+   defs="$defs -DHAVE_STORE -DSTORE_MYSQL"
+fi
+
+if test "$STORE" = "fs"; then
+   echo "message store: fs"
+   defs="$defs -DHAVE_STORE -DSTORE_FS"
 fi
 
 if test "$want_spamsum" = "yes"; then
@@ -6454,7 +6505,7 @@ else
    echo "tokens are case sensitive: no"
 fi
 
-if test "$want_lmtp" = "yes" && test "$want_outgoing_smtp" = "no"; then
+if test "$want_lmtp" = "yes"; then
    echo "local delivery: LMTP"
    defs="$defs -DHAVE_LMTP"
 else
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -75,7 +75,6 @@ sqlite3_libs=""
 spamsum_libs=""
 os=`uname -s`
 
-want_outgoing_smtp="no"
 want_language_detection="no"
 
 
@@ -278,6 +277,36 @@ AC_ARG_WITH(userdb,
 
 
 
+dnl message store
+
+AC_ARG_WITH(store,
+[  --with-store[[=mysql|fs]]         use either mysql database or the local filesystem to keep emails (default: none)],[
+  if test "$withval" != "no" -a "$withval" != "yes"; then
+    STORE=$withval
+  fi
+
+  if test "$withval" = "mysql"; then
+     AC_CHECK_PROG(MYSQL_CONFIG, mysql_config, yes)
+
+     if test x$MYSQL_CONFIG = xyes; then
+       have_mysql="yes"
+     fi
+
+     if test "$have_mysql" = "yes"; then
+            dnl AC_DEFINE(USE_MYSQL, 1, [MySQL database support enabled])
+
+            mysql_includes=`mysql_config --cflags`
+            mysql_libs=`mysql_config --libs_r`
+     else
+        echo "MySQL support is not found"
+        exit 1;
+     fi
+   fi
+
+])
+
+
+
 dnl the blackhole feature
 
 AC_ARG_ENABLE(policy,
@@ -371,28 +400,6 @@ dnl lmtp support
 dnl language detection
     AC_ARG_ENABLE(language-detection,
           [  --enable-language-detection use the language detection feature (experimental)], want_language_detection=$enableval, want_language_detection="no")
-
-
-dnl external store
-dnl    AC_ARG_ENABLE(store,
-dnl          [  --enable-store          use external store to store emails for later retraining], want_store=$enableval, want_store="no")
-
-dnl    if test "$want_store" = "yes"; then
-dnl        defs="$defs -DHAVE_STORE"
-dnl        clapfstore="clapfstore"
-dnl        store_obj="store.o"
-dnl	clapfstore_install="install-clapfstore"
-dnl        have_store="yes"
-dnl    fi
-
-
-dnl outgoing smtp support
-    AC_ARG_ENABLE(outgoing-smtp,
-          [  --enable-outgoing-smtp  enable outgoing SMTP server mode], want_outgoing_smtp=$enableval, want_outgoing_smtp="no")
-
-    if test "$want_outgoing_smtp" = "yes"; then
-       AC_DEFINE_UNQUOTED(OUTGOING_SMTP, 1, [enable outgoing smtp mode])
-    fi
 
 
 dnl enable spamsum support
@@ -647,10 +654,14 @@ if test "$TOKENDB" = "sqlite3"; then
    db_install="install-sqlite3"
 fi
 
-if test "$have_store" = "yes"; then
-   echo "store: clapfstore"
-else
-   echo "store: internal"
+if test "$STORE" = "mysql"; then
+   echo "message store: mysql"
+   defs="$defs -DHAVE_STORE -DSTORE_MYSQL"
+fi
+
+if test "$STORE" = "fs"; then
+   echo "message store: fs"
+   defs="$defs -DHAVE_STORE -DSTORE_FS"
 fi
 
 if test "$want_spamsum" = "yes"; then
@@ -674,7 +685,7 @@ else
    echo "tokens are case sensitive: no"
 fi
 
-if test "$want_lmtp" = "yes" && test "$want_outgoing_smtp" = "no"; then
+if test "$want_lmtp" = "yes"; then
    echo "local delivery: LMTP"
    defs="$defs -DHAVE_LMTP"
 else
