added postgresql support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -604,6 +604,7 @@ LIBOBJS
 DATAROOTDIR
 LOCALSTATEDIR
 CFGDIR
+PSQL_CONFIG
 MYSQL_CONFIG
 id_bin
 sqlite3_batch
@@ -613,10 +614,9 @@ spamsum
 spamsum_libs
 db_install
 sql_obj
-ldap_libs
 user_obj
-mysql_libs
-mysql_includes
+sql_libs
+sql_includes
 test
 preparesql
 spamdrop_install
@@ -1355,7 +1355,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-store[=fs|nfs]         use either the local filesystem or NFS to keep emails (default: none)
-  --with-tokendb[=mysql|sqlite3]  use either mysql or sqlite3 database holding tokens (default: none)
+  --with-tokendb[=mysql|psql|sqlite3]  use either mysql or psql or sqlite3 database holding tokens (default: none)
   --with-clapf-user=username      what user the clapf daemon shall be run as
 
 Some influential environment variables:
@@ -3468,7 +3468,6 @@ done
 
 
 
-
 have_libclamav="no"
 have_libtool="no"
 have_clamd="no"
@@ -3502,7 +3501,6 @@ defs=""
 objs=""
 user_obj=""
 sql_obj=""
-ldap_libs=""
 sqlite3_libs=""
 spamsum_libs=""
 sqlite3_batch=""
@@ -4169,12 +4167,65 @@ fi
 
      if test "$have_mysql" = "yes"; then
 
-            mysql_includes=`mysql_config --cflags`
-            mysql_libs=`mysql_config --libs_r`
+            sql_includes=`mysql_config --cflags`
+            sql_libs=`mysql_config --libs_r`
      else
         echo "MySQL support is not found"
         exit 1;
      fi
+   fi
+
+   if test "$withval" = "psql"; then
+      # Extract the first word of "pg_config", so it can be a program name with args.
+set dummy pg_config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_PSQL_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$PSQL_CONFIG"; then
+  ac_cv_prog_PSQL_CONFIG="$PSQL_CONFIG" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_PSQL_CONFIG="yes"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+fi
+fi
+PSQL_CONFIG=$ac_cv_prog_PSQL_CONFIG
+if test -n "$PSQL_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $PSQL_CONFIG" >&5
+$as_echo "$PSQL_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+
+      if test x$MYSQL_CONFIG = xyes; then
+        have_psql="yes"
+      fi
+
+      if test "$have_psql" = "yes"; then
+
+            sql_includes="-I`pg_config --includedir`"
+            sql_libs="-L`pg_config --libdir`"
+      else
+         echo "PSQL support is not found"
+         exit 1;
+      fi
    fi
 
 
@@ -4381,8 +4432,8 @@ fi
 
      if test "$have_mysql" = "yes"; then
 
-            mysql_includes=`mysql_config --cflags`
-            mysql_libs=`mysql_config --libs_r`
+            sql_includes=`mysql_config --cflags`
+            sql_libs=`mysql_config --libs_r`
             have_spamdrop="yes"
             parsembox="$parsembox"
             preparesql="prepare-sql aphash "
@@ -4398,6 +4449,67 @@ fi
   fi
 
 
+  if test "$withval" = "psql"; then
+
+    # Extract the first word of "pg_config", so it can be a program name with args.
+set dummy pg_config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_PSQL_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$PSQL_CONFIG"; then
+  ac_cv_prog_PSQL_CONFIG="$PSQL_CONFIG" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_PSQL_CONFIG="yes"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+fi
+fi
+PSQL_CONFIG=$ac_cv_prog_PSQL_CONFIG
+if test -n "$PSQL_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $PSQL_CONFIG" >&5
+$as_echo "$PSQL_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+
+     if test x$PSQL_CONFIG = xyes; then
+       have_psql="yes"
+     fi
+
+     if test "$have_psql" = "yes"; then
+
+            sql_includes="-I`pg_config --includedir`"
+            sql_libs="-L`pg_config --libdir`"
+            have_spamdrop="yes"
+            parsembox="$parsembox"
+            preparesql="prepare-sql aphash "
+            spamdrop="spamdrop"
+            spamdrop_install="install-spamdrop"
+            db_install="install-psql-new"
+
+            test="test"
+     else
+        echo "PSQL support is not found"
+        exit 1;
+     fi
+  fi
 
   if test "$withval" = "mydb"; then
      have_spamdrop="yes"
@@ -4689,6 +4801,11 @@ if test "$TOKENDB" = "mysql"; then
    sql_obj="mysql.o "
 fi
 
+if test "$TOKENDB" = "psql"; then
+   defs="$defs -DHAVE_PSQL"
+   sql_obj="psql.o "
+fi
+
 if test "$TOKENDB" = "mydb"; then
    defs="$defs -DHAVE_MYDB"
    sql_obj="mydb.o"
@@ -4926,12 +5043,15 @@ if test "$have_tre" = "yes"; then
 fi
 
 if test "$have_sqlite3" = "yes"; then
-   sqlite3_libs="-lsqlite3 -lpthread"
+   sql_libs="-lsqlite3 -lpthread"
 fi
 
+if test "$have_psql" = "yes"; then
+   sql_libs="-lpq"
+fi
 
 if test "$have_icc_guide" = "yes" && test "$have_mysql" = "yes"; then
-   mysql_libs="$mysql_libs -lguide"
+   sql_libs="$sql_libs -lguide"
 fi
 
 
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -28,10 +28,9 @@ AC_SUBST(spamdrop)
 AC_SUBST(spamdrop_install)
 AC_SUBST(preparesql)
 AC_SUBST(test)
-AC_SUBST(mysql_includes)
-AC_SUBST(mysql_libs)
+AC_SUBST(sql_includes)
+AC_SUBST(sql_libs)
 AC_SUBST(user_obj)
-AC_SUBST(ldap_libs)
 AC_SUBST(sql_obj)
 AC_SUBST(db_install)
 AC_SUBST(spamsum_libs)
@@ -74,7 +73,6 @@ defs=""
 objs=""
 user_obj=""
 sql_obj=""
-ldap_libs=""
 sqlite3_libs=""
 spamsum_libs=""
 sqlite3_batch=""
@@ -309,12 +307,30 @@ AC_ARG_WITH(store,
      if test "$have_mysql" = "yes"; then
             dnl AC_DEFINE(USE_MYSQL, 1, [MySQL database support enabled])
 
-            mysql_includes=`mysql_config --cflags`
-            mysql_libs=`mysql_config --libs_r`
+            sql_includes=`mysql_config --cflags`
+            sql_libs=`mysql_config --libs_r`
      else
         echo "MySQL support is not found"
         exit 1;
      fi
+   fi
+
+   if test "$withval" = "psql"; then
+      AC_CHECK_PROG(PSQL_CONFIG, pg_config, yes)
+
+      if test x$MYSQL_CONFIG = xyes; then
+        have_psql="yes"
+      fi
+
+      if test "$have_psql" = "yes"; then
+            dnl AC_DEFINE(USE_PSQL, 1, [PSQL database support enabled])
+
+            sql_includes="-I`pg_config --includedir`"
+            sql_libs="-L`pg_config --libdir`"
+      else
+         echo "PSQL support is not found"
+         exit 1;
+      fi
    fi
 
 ])
@@ -347,7 +363,7 @@ fi
 
 
 AC_ARG_WITH(tokendb,
-[  --with-tokendb[[=mysql|sqlite3]]  use either mysql or sqlite3 database holding tokens (default: none)],[
+[  --with-tokendb[[=mysql|psql|sqlite3]]  use either mysql or psql or sqlite3 database holding tokens (default: none)],[
   if test "$withval" != "no" -a "$withval" != "yes"; then
     TOKENDB=$withval
   fi
@@ -392,8 +408,8 @@ AC_ARG_WITH(tokendb,
      if test "$have_mysql" = "yes"; then
             dnl AC_DEFINE(USE_MYSQL, 1, [MySQL database support enabled])
 
-            mysql_includes=`mysql_config --cflags`
-            mysql_libs=`mysql_config --libs_r`
+            sql_includes=`mysql_config --cflags`
+            sql_libs=`mysql_config --libs_r`
             have_spamdrop="yes"
             parsembox="$parsembox"
             preparesql="prepare-sql aphash "
@@ -409,6 +425,32 @@ AC_ARG_WITH(tokendb,
   fi
 
 
+  if test "$withval" = "psql"; then
+
+    AC_CHECK_PROG(PSQL_CONFIG, pg_config, yes)
+
+     if test x$PSQL_CONFIG = xyes; then
+       have_psql="yes"
+     fi
+
+     if test "$have_psql" = "yes"; then
+            dnl AC_DEFINE(USE_PSQL, 1, [PSQL database support enabled])
+
+            sql_includes="-I`pg_config --includedir`"
+            sql_libs="-L`pg_config --libdir`"
+            have_spamdrop="yes"
+            parsembox="$parsembox"
+            preparesql="prepare-sql aphash "
+            spamdrop="spamdrop"
+            spamdrop_install="install-spamdrop"
+            db_install="install-psql-new"
+
+            test="test"
+     else
+        echo "PSQL support is not found"
+        exit 1;
+     fi
+  fi
 
   if test "$withval" = "mydb"; then
      have_spamdrop="yes"
@@ -563,6 +605,11 @@ fi
 if test "$TOKENDB" = "mysql"; then
    defs="$defs -DHAVE_MYSQL"
    sql_obj="mysql.o "
+fi
+
+if test "$TOKENDB" = "psql"; then
+   defs="$defs -DHAVE_PSQL"
+   sql_obj="psql.o "
 fi
 
 if test "$TOKENDB" = "mydb"; then
@@ -799,12 +846,15 @@ if test "$have_tre" = "yes"; then
 fi
 
 if test "$have_sqlite3" = "yes"; then
-   sqlite3_libs="-lsqlite3 -lpthread"
+   sql_libs="-lsqlite3 -lpthread"
 fi
 
+if test "$have_psql" = "yes"; then
+   sql_libs="-lpq"
+fi
 
 if test "$have_icc_guide" = "yes" && test "$have_mysql" = "yes"; then
-   mysql_libs="$mysql_libs -lguide"
+   sql_libs="$sql_libs -lguide"
 fi
 
 
